//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeRunner2016 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MazeRunner2016Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MazeRunner2016Settings defaultInstance = ((MazeRunner2016Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MazeRunner2016Settings())));
        
        public static MazeRunner2016Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int numberOfThreads {
            get {
                return ((int)(this["numberOfThreads"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Prim")]
        public string createMazeAlgo {
            get {
                return ((string)(this["createMazeAlgo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFS or DFS")]
        public string solveMazeAlgo {
            get {
                return ((string)(this["solveMazeAlgo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dsf")]
        public string dfsdf {
            get {
                return ((string)(this["dfsdf"]));
            }
            set {
                this["dfsdf"] = value;
            }
        }
    }
}
